[book]
authors = ["giuliano panzironi"]
language = "en"
multilingual = false
src = "src"
title = "bookmarks on programming"

[output.html]
site-url = "/programming/"
git-repository-url = "https://github.com/giulianopz/programming"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/giulianopz/programming/edit/main/{path} "
