version: '3'

tasks:
  serve:
    cmds:
      # cargo install mdbook
      - mdbook serve . -p 8000 -n 127.0.0.1 
  linkcheck:
    cmds:
      # python -m pip install linkcheckmd
      - ~/utilvenv/bin/python -m linkcheckmd ./src/
