version: '3'

tasks:
  serve:
    cmds:
      # cargo install mdbook
      - mdbook serve . -p 8000 -n 127.0.0.1 
  linkcheck:
    cmds:
      # go install github.com/giulianopz/mdlinkcheck
      - mdlinkcheck --dir ./src/ | grep -v 200
  archive:
    cmds:
      - for i in $(grep -rEo --no-filename "https?://[^][ )]+" src/*.md); do sed -e 's/^http:\/\///g' -e 's/^https:\/\///g' -e 's/\//-/g' <<<$i ; done
