name: book

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3       
    - name: Install MDBook
      run: cargo install mdbook
    - name: Build Book
      run: mdbook build .
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: book # The folder the action should deploy.
